[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=9.2"]
build-backend = "setuptools.build_meta"

[project]
name = "human-sudoku-solver"
dynamic = ["version"]
requires-python = ">=3.14"
description = "Use human logic to help solve sudoku"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENCE"]
keywords = ["sudoku"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
Repository = "https://github.com/blm34/human-sudoku-solver/"
Issues = "https://github.com/blm34/human-sudoku-solver/issues"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]
tests = [
    "pytest>=9.1.1",
]
